<?php
/**
 * SBG_SEO_Meta_Box
 *
 * Adds a "Smart Blog Generator — SEO Checks" meta box to the post edit
 * screen for any post generated by this plugin.
 *
 * The meta box performs four lightweight checks and renders each as a
 * colour-coded badge:
 *
 *   1. SEO title length        — ideal ≤ 60 characters (Yoast/RankMath field,
 *                                falls back to post title)
 *   2. Meta description length — ideal 50–160 characters
 *   3. Keyword in first <p>    — focus keyword present in the opening paragraph
 *   4. Keyword in H1           — focus keyword present in the H1 heading
 *
 * The meta box is only shown on posts that have the `_sbg_generated` meta
 * flag set by SBG_Post_Creator, so it does not appear on hand-written posts.
 *
 * No data is saved here — this is a read-only display component.
 *
 * @package Smart_Blog_Generator
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers and renders the SEO indicator meta box.
 */
class SBG_SEO_Meta_Box {

	// -------------------------------------------------------------------------
	// Registration
	// -------------------------------------------------------------------------

	/**
	 * Registers the meta box on post edit screens.
	 *
	 * Hooked to add_meta_boxes by SBG_Admin_Controller. The meta box is
	 * intentionally registered for all posts — the renderer checks the
	 * _sbg_generated flag and outputs a "not generated" notice for others.
	 */
	public static function register(): void {
		add_meta_box(
			'sbg-seo-metabox',
			__( 'Smart Blog Generator — SEO Checks', 'smart-blog-generator' ),
			[ self::class, 'render' ],
			'post',     // post type
			'side',     // context
			'default'   // priority
		);
	}

	// -------------------------------------------------------------------------
	// Renderer
	// -------------------------------------------------------------------------

	/**
	 * Renders the SEO checks meta box for the given post.
	 *
	 * Reads post meta saved during generation and the current post content
	 * to perform the four checks. Results are displayed as colour-coded
	 * badges (pass / warn / fail) in a two-column table.
	 *
	 * @param WP_Post $post The post being edited.
	 */
	public static function render( WP_Post $post ): void {
		// Only show full analysis for SBG-generated posts.
		$is_generated = (bool) get_post_meta( $post->ID, '_sbg_generated', true );

		if ( ! $is_generated ) {
			echo '<p style="color:#50575e;">';
			esc_html_e( 'This post was not generated by Smart Blog Generator.', 'smart-blog-generator' );
			echo '</p>';
			return;
		}

		// ── Retrieve stored values ────────────────────────────────────────────

		$keyword = (string) get_post_meta( $post->ID, '_sbg_keyword', true );

		// SEO title: prefer Yoast field, then RankMath, then post title.
		$seo_title = (string) get_post_meta( $post->ID, '_yoast_wpseo_title', true );
		if ( '' === $seo_title ) {
			$seo_title = (string) get_post_meta( $post->ID, 'rank_math_title', true );
		}
		if ( '' === $seo_title ) {
			$seo_title = $post->post_title;
		}

		// Meta description: prefer Yoast, then RankMath.
		$meta_desc = (string) get_post_meta( $post->ID, '_yoast_wpseo_metadesc', true );
		if ( '' === $meta_desc ) {
			$meta_desc = (string) get_post_meta( $post->ID, 'rank_math_description', true );
		}

		$content   = $post->post_content;

		// ── Run the four checks ───────────────────────────────────────────────
		$checks = self::run_checks( $seo_title, $meta_desc, $keyword, $content );

		// ── Generated-at timestamp ────────────────────────────────────────────
		$generated_at = (string) get_post_meta( $post->ID, '_sbg_generated_at', true );

		// ── Internal link suggestions ─────────────────────────────────────────
		$internal_links = get_post_meta( $post->ID, '_sbg_internal_links', true );

		// ── Output ────────────────────────────────────────────────────────────
		echo '<div id="sbg-seo-metabox-content">';

		echo '<table style="width:100%;border-collapse:collapse;">';
		echo '<tbody>';

		foreach ( $checks as $check ) {
			self::render_check_row( $check );
		}

		echo '</tbody>';
		echo '</table>';

		// Generation timestamp.
		if ( '' !== $generated_at ) {
			echo '<p style="margin-top:10px;color:#50575e;font-size:11px;">';
			printf(
				/* translators: %s: formatted date/time string */
				esc_html__( 'Generated: %s', 'smart-blog-generator' ),
				esc_html( date_i18n( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $generated_at ) ) )
			);
			echo '</p>';
		}

		// Internal link suggestions.
		if ( is_array( $internal_links ) && ! empty( $internal_links ) ) {
			echo '<hr style="margin:10px 0;">';
			echo '<p style="font-weight:600;margin-bottom:4px;">';
			esc_html_e( 'Suggested Internal Links:', 'smart-blog-generator' );
			echo '</p>';
			echo '<ul style="margin:0;padding-left:16px;">';
			foreach ( $internal_links as $link ) {
				$anchor  = sanitize_text_field( $link['anchor']         ?? '' );
				$target  = sanitize_text_field( $link['target_keyword'] ?? '' );
				if ( '' === $anchor ) {
					continue;
				}
				echo '<li style="font-size:12px;color:#50575e;">';
				echo '<strong>' . esc_html( $anchor ) . '</strong>';
				if ( '' !== $target ) {
					echo ' → ' . esc_html( $target );
				}
				echo '</li>';
			}
			echo '</ul>';
		}

		echo '</div><!-- #sbg-seo-metabox-content -->';
	}

	// -------------------------------------------------------------------------
	// Check logic
	// -------------------------------------------------------------------------

	/**
	 * Runs all four SEO indicator checks and returns an array of result arrays.
	 *
	 * Each result:
	 *   label  string  Display label for the check.
	 *   status string  'pass' | 'warn' | 'fail'
	 *   detail string  Tooltip/detail text (e.g. "52 chars").
	 *
	 * @param string $seo_title SEO title to evaluate.
	 * @param string $meta_desc Meta description to evaluate.
	 * @param string $keyword   Focus keyword to look for.
	 * @param string $content   Full post content HTML.
	 *
	 * @return list<array{label: string, status: string, detail: string}>
	 */
	private static function run_checks(
		string $seo_title,
		string $meta_desc,
		string $keyword,
		string $content
	): array {
		$checks = [];

		// ── Check 1: SEO title length ─────────────────────────────────────────
		$title_len = mb_strlen( wp_strip_all_tags( $seo_title ) );

		if ( 0 === $title_len ) {
			$title_status = 'fail';
			$title_detail = __( 'No SEO title set', 'smart-blog-generator' );
		} elseif ( $title_len <= 60 ) {
			$title_status = 'pass';
			/* translators: %d: character count */
			$title_detail = sprintf( __( '%d chars (≤ 60 ✓)', 'smart-blog-generator' ), $title_len );
		} else {
			$title_status = 'warn';
			/* translators: %d: character count */
			$title_detail = sprintf( __( '%d chars (> 60 — consider shortening)', 'smart-blog-generator' ), $title_len );
		}

		$checks[] = [
			'label'  => __( 'SEO Title Length', 'smart-blog-generator' ),
			'status' => $title_status,
			'detail' => $title_detail,
		];

		// ── Check 2: Meta description length ─────────────────────────────────
		$desc_len = mb_strlen( wp_strip_all_tags( $meta_desc ) );

		if ( 0 === $desc_len ) {
			$desc_status = 'fail';
			$desc_detail = __( 'No meta description set', 'smart-blog-generator' );
		} elseif ( $desc_len < 50 ) {
			$desc_status = 'warn';
			/* translators: %d: character count */
			$desc_detail = sprintf( __( '%d chars (too short — aim for 50–160)', 'smart-blog-generator' ), $desc_len );
		} elseif ( $desc_len <= 160 ) {
			$desc_status = 'pass';
			/* translators: %d: character count */
			$desc_detail = sprintf( __( '%d chars (50–160 ✓)', 'smart-blog-generator' ), $desc_len );
		} else {
			$desc_status = 'warn';
			/* translators: %d: character count */
			$desc_detail = sprintf( __( '%d chars (> 160 — may be truncated in SERPs)', 'smart-blog-generator' ), $desc_len );
		}

		$checks[] = [
			'label'  => __( 'Meta Description Length', 'smart-blog-generator' ),
			'status' => $desc_status,
			'detail' => $desc_detail,
		];

		// ── Check 3: Keyword in first paragraph ───────────────────────────────
		// Extract the plain text of the first <p> element from the content.
		$kw_intro_status = 'fail';
		$kw_intro_detail = __( 'Keyword not found in first paragraph', 'smart-blog-generator' );

		if ( '' !== $keyword && '' !== $content ) {
			$first_para_text = self::extract_first_paragraph_text( $content );

			if ( '' !== $first_para_text && false !== mb_stripos( $first_para_text, $keyword ) ) {
				$kw_intro_status = 'pass';
				$kw_intro_detail = __( 'Found ✓', 'smart-blog-generator' );
			} elseif ( '' === $first_para_text ) {
				$kw_intro_status = 'warn';
				$kw_intro_detail = __( 'Could not locate first paragraph', 'smart-blog-generator' );
			}
		} elseif ( '' === $keyword ) {
			$kw_intro_status = 'warn';
			$kw_intro_detail = __( 'No keyword saved', 'smart-blog-generator' );
		}

		$checks[] = [
			'label'  => __( 'Keyword in First Paragraph', 'smart-blog-generator' ),
			'status' => $kw_intro_status,
			'detail' => $kw_intro_detail,
		];

		// ── Check 4: Keyword in H1 ────────────────────────────────────────────
		$kw_h1_status = 'fail';
		$kw_h1_detail = __( 'Keyword not found in H1', 'smart-blog-generator' );

		if ( '' !== $keyword && '' !== $content ) {
			$h1_text = self::extract_first_h1_text( $content );

			if ( '' !== $h1_text && false !== mb_stripos( $h1_text, $keyword ) ) {
				$kw_h1_status = 'pass';
				$kw_h1_detail = __( 'Found ✓', 'smart-blog-generator' );
			} elseif ( '' === $h1_text ) {
				$kw_h1_status = 'warn';
				$kw_h1_detail = __( 'No H1 found in content', 'smart-blog-generator' );
			}
		} elseif ( '' === $keyword ) {
			$kw_h1_status = 'warn';
			$kw_h1_detail = __( 'No keyword saved', 'smart-blog-generator' );
		}

		$checks[] = [
			'label'  => __( 'Keyword in H1', 'smart-blog-generator' ),
			'status' => $kw_h1_status,
			'detail' => $kw_h1_detail,
		];

		return $checks;
	}

	// -------------------------------------------------------------------------
	// Content extraction helpers
	// -------------------------------------------------------------------------

	/**
	 * Extracts the plain text of the first <p> element from an HTML string.
	 *
	 * Uses a simple regex rather than DOMDocument to avoid requiring the
	 * php-xml extension and to handle partial/malformed HTML gracefully.
	 *
	 * @param string $html Post content HTML.
	 *
	 * @return string Plain text of the first <p>, or empty string if none found.
	 */
	private static function extract_first_paragraph_text( string $html ): string {
		if ( ! preg_match( '/<p\b[^>]*>(.*?)<\/p>/is', $html, $matches ) ) {
			return '';
		}
		return wp_strip_all_tags( $matches[1] );
	}

	/**
	 * Extracts the plain text of the first <h1> element from an HTML string.
	 *
	 * @param string $html Post content HTML.
	 *
	 * @return string Plain text of the first <h1>, or empty string if none found.
	 */
	private static function extract_first_h1_text( string $html ): string {
		if ( ! preg_match( '/<h1\b[^>]*>(.*?)<\/h1>/is', $html, $matches ) ) {
			return '';
		}
		return wp_strip_all_tags( $matches[1] );
	}

	// -------------------------------------------------------------------------
	// Row renderer helper
	// -------------------------------------------------------------------------

	/**
	 * Outputs a single two-column <tr> for one SEO check result.
	 *
	 * @param array{label: string, status: string, detail: string} $check Check result array.
	 */
	private static function render_check_row( array $check ): void {
		// Map status to badge CSS class (defined in the controller's inline CSS).
		$badge_class = match ( $check['status'] ) {
			'pass'  => 'sbg-badge sbg-badge-pass',
			'warn'  => 'sbg-badge sbg-badge-warn',
			default => 'sbg-badge sbg-badge-fail',
		};

		echo '<tr style="border-bottom:1px solid #f0f0f1;">';

		// Label cell.
		printf(
			'<td style="padding:6px 4px;font-size:12px;">%s</td>',
			esc_html( $check['label'] )
		);

		// Badge cell.
		printf(
			'<td style="padding:6px 4px;text-align:right;"><span class="%1$s" title="%2$s">%2$s</span></td>',
			esc_attr( $badge_class ),
			esc_attr( $check['detail'] )
		);

		echo '</tr>';
	}
}
