<?php
/**
 * Plugin Name:       Smart Blog Generator
 * Plugin URI:        https://example.com/smart-blog-generator
 * Description:       Generates SEO-optimised blog posts via the Anthropic Claude API, pulls a featured image from Unsplash, and saves the result as a WordPress draft ready for human review.
 * Version:           1.0.0
 * Requires at least: 6.0
 * Requires PHP:      8.1
 * Author:            Smart Blog Generator
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       smart-blog-generator
 */

// Prevent direct file access — all plugin files share this guard.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------------------
// Plugin-wide constants
// ---------------------------------------------------------------------------
define( 'SBG_VERSION',     '1.0.0' );
define( 'SBG_PLUGIN_DIR',  plugin_dir_path( __FILE__ ) );
define( 'SBG_PLUGIN_URL',  plugin_dir_url( __FILE__ ) );
define( 'SBG_PLUGIN_FILE', __FILE__ );

/** Anthropic model used for all generation requests. */
define( 'SBG_ANTHROPIC_MODEL', 'claude-sonnet-4-20250514' );

/** Anthropic Messages API endpoint. */
define( 'SBG_ANTHROPIC_ENDPOINT', 'https://api.anthropic.com/v1/messages' );

/** Unsplash search endpoint. */
define( 'SBG_UNSPLASH_ENDPOINT', 'https://api.unsplash.com/search/photos' );

// ---------------------------------------------------------------------------
// Load class files
// ---------------------------------------------------------------------------
// Includes — core business logic (no admin dependencies).
require_once SBG_PLUGIN_DIR . 'includes/class-api-handler.php';
require_once SBG_PLUGIN_DIR . 'includes/class-image-fetcher.php';
require_once SBG_PLUGIN_DIR . 'includes/class-post-creator.php';

// Admin — only load on admin requests to avoid unnecessary overhead on the
// front end. is_admin() is true for both admin-ajax.php and normal admin pages.
if ( is_admin() ) {
	require_once SBG_PLUGIN_DIR . 'admin/class-settings-page.php';
	require_once SBG_PLUGIN_DIR . 'admin/class-generator-page.php';
	require_once SBG_PLUGIN_DIR . 'admin/class-seo-meta-box.php';
	require_once SBG_PLUGIN_DIR . 'admin/class-admin-controller.php';
}

// ---------------------------------------------------------------------------
// Front-end FAQ schema output
// ---------------------------------------------------------------------------
// When a post generated by this plugin is viewed on the front end, output the
// saved JSON-LD FAQ schema in <head>. The schema is stored as post meta so
// it never gets stripped by wp_kses_post during post saving.
add_action( 'wp_head', 'sbg_output_faq_schema' );

/**
 * Outputs the FAQ JSON-LD schema block for generated posts.
 *
 * Runs on wp_head. Exits silently if the current page is not a singular post
 * or if no FAQ schema meta was saved during generation.
 */
function sbg_output_faq_schema(): void {
	if ( ! is_singular( 'post' ) ) {
		return;
	}

	$post_id = (int) get_the_ID();
	$schema  = get_post_meta( $post_id, '_sbg_faq_schema', true );

	if ( empty( $schema ) ) {
		return;
	}

	// The schema is already a validated JSON string (encoded by wp_json_encode).
	// Output inside a standard JSON-LD script tag.
	echo '<script type="application/ld+json">' . "\n";
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON-LD does not need HTML escaping; escaping would break the schema.
	echo $schema . "\n";
	echo '</script>' . "\n";
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------
/**
 * Fires after all plugins are loaded so our classes can safely interact with
 * third-party plugins (e.g. Yoast SEO capability checks).
 */
add_action( 'plugins_loaded', 'sbg_init' );

/**
 * Instantiates the admin controller, which registers all admin hooks.
 * The controller is only created on admin requests (see the is_admin() guard
 * in the require_once block above).
 */
function sbg_init(): void {
	if ( is_admin() ) {
		SBG_Admin_Controller::instance();
	}
}

// ---------------------------------------------------------------------------
// Activation
// ---------------------------------------------------------------------------
register_activation_hook( SBG_PLUGIN_FILE, 'sbg_activate' );

/**
 * Sets default option values on first activation.
 * Uses add_option() so existing values are never overwritten on reactivation.
 */
function sbg_activate(): void {
	add_option( 'sbg_anthropic_api_key',   '' );
	add_option( 'sbg_unsplash_access_key', '' );
}
